### ISSUE TITLE
Fix hex encoding issue

### ISSUE THREAD

**Issue by chardskarth** [bauglir/render-plantuml#9]
Without this fix, it shows this error: 
```
The plugin you are using seems to generated a bad URL.
This URL does not look like DEFLATE data.
It looks like your plugin is using HUFFMAN encoding.
```

![image](https://github.com/user-attachments/assets/257fe5cc-6659-4010-a0ee-59fe84f1c7a4)

According to plantuml's [documentation](https://plantuml.com/text-encoding), to pass hex encoding, the url needs to be prepended with `~h` instead of `-hex-`

**Comment by bauglir** [comment]
Thanks for reporting and the proposed fix. There were some issues getting this published, but it should now be available as [v0.3.2](https://github.com/bauglir/render-plantuml/releases/tag/v0.3.2).
